/**
 * CHALLENGE 1
 * 
 * Create function called "mult" and it will have 3 parameters.
 * Create new variable and assign it result of multiplication of all 3 parameters.
 * Print to the console results.
 * Don't use "return".
 */

 function mult(a, b, c) {
     let z = a * b * c;
     console.log(z);
 }

 mult(3,1,3);

/**
 * CHALLENGE 2
 * 
 * Create a function "concatenatedStrings" and it will have 2 parameters.
 * and this function will return concatenated string.
 */

 function concatenatedStrings(x, y) {
    return x + " " + y;
}

console.log(concatenatedStrings("Hello","World"));



